# Modeling

In this notebook, we train machine learning models to predict delivery time.

We use the preprocessed training data to train the models and the test data to evaluate their performance.


In [21]:
import pandas as pd
from sklearn.linear_model import LinearRegression

## Load Preprocessed Data

We load the training and test datasets created during preprocessing.


In [22]:
X_train = pd.read_csv("../data/X_train_preprocessed.csv")
X_test = pd.read_csv("../data/X_test_preprocessed.csv")

y_train = pd.read_csv("../data/y_train.csv").squeeze() # squeeze() converts the one-column DataFrame into a Series
y_test = pd.read_csv("../data/y_test.csv").squeeze()

## Verify Loaded Data

We check the shapes of the loaded datasets before training the model.


In [23]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (33217, 29)
X_test: (8305, 29)
y_train: (33217,)
y_test: (8305,)


## Linear Regression

Linear Regression is a supervised learning algorithm used to predict a numerical value.

We use it as our first baseline model to predict `Time_taken(min)`.


In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

## Train the Model

We train the Linear Regression model using the training features and their corresponding delivery times.


In [25]:
model.fit(
    X_train,
    y_train
)

print("Model trained successfully.")

Model trained successfully.


In [26]:
print(model)

LinearRegression()


## Linear Regression — Evaluation

After training the Linear Regression model, we evaluate its performance on the test set using several regression metrics:

* **MAE**: average prediction error in minutes.
* **MSE**: average squared prediction error.
* **RMSE**: prediction error in minutes, with more importance given to large errors.
* **R²**: proportion of the variation in delivery time explained by the model.
* **Adjusted R²**: R² adjusted according to the number of features used by the model.

These metrics allow us to evaluate the model from different perspectives and compare it with other regression models.


In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions
y_pred = model.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Adjusted R²
n = len(y_test)       # number of observations
p = X_test.shape[1]   # number of features

adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

# Display results
print("Linear Regression Results")
print("-------------------------")
print("MAE        :", round(mae, 2), "minutes")
print("MSE        :", round(mse, 2))
print("RMSE       :", round(rmse, 2), "minutes")
print("R²         :", round(r2, 4))
print("Adjusted R²:", round(adjusted_r2, 4))

Linear Regression Results
-------------------------
MAE        : 5.07 minutes
MSE        : 41.24
RMSE       : 6.42 minutes
R²         : 0.5361
Adjusted R²: 0.5344


## Decision Tree Regression

Decision Tree Regression predicts a numerical value by splitting the data into smaller groups using feature values.

We use it as a second model to compare its performance with Linear Regression.


In [28]:
from sklearn.tree import DecisionTreeRegressor

tree_model = DecisionTreeRegressor(
    random_state=42
)

## Train the Decision Tree

We train the Decision Tree using the training features and the corresponding delivery times.


In [29]:
tree_model.fit(
    X_train,
    y_train
)

print("Decision Tree trained successfully.")

Decision Tree trained successfully.


## Make Predictions

We use the trained Decision Tree to predict delivery times for the test data.


In [30]:
tree_pred = tree_model.predict(X_test)

print("First 10 predictions:")
print(tree_pred[:10])

First 10 predictions:
[24. 27. 18. 42. 23. 42. 10. 15. 23. 50.]


## Evaluate the Decision Tree

We evaluate the Decision Tree using MAE, MSE, RMSE, and R².

These metrics allow us to compare the Decision Tree with our Linear Regression baseline.


In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions
tree_pred = tree_model.predict(X_test)

# Metrics
tree_mae = mean_absolute_error(y_test, tree_pred)
tree_mse = mean_squared_error(y_test, tree_pred)
tree_rmse = np.sqrt(tree_mse)
tree_r2 = r2_score(y_test, tree_pred)

# Adjusted R²
n = len(y_test)
p = X_test.shape[1]

tree_adjusted_r2 = 1 - (1 - tree_r2) * (n - 1) / (n - p - 1)

# Display results
print("Decision Tree Results")
print("---------------------")
print("MAE        :", round(tree_mae, 2), "minutes")
print("MSE        :", round(tree_mse, 2))
print("RMSE       :", round(tree_rmse, 2), "minutes")
print("R²         :", round(tree_r2, 4))
print("Adjusted R²:", round(tree_adjusted_r2, 4))

Decision Tree Results
---------------------
MAE        : 4.79 minutes
MSE        : 40.81
RMSE       : 6.39 minutes
R²         : 0.5409
Adjusted R²: 0.5393


## Compare the Baseline Models

The Decision Tree and Linear Regression models have similar performance on the test set.

The Decision Tree slightly reduces MAE, while Linear Regression has slightly better MSE, RMSE, and R².

These results show that neither model has a clear advantage at this stage.


## Random Forest Regression

Random Forest is an ensemble regression algorithm that combines multiple Decision Trees.

Using several trees can improve generalization compared with a single Decision Tree and can help reduce overfitting.


In [32]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

## Train the Random Forest

We train the Random Forest using the training data.

The test data remains unseen during training.


In [33]:
rf_model.fit(
    X_train,
    y_train
)

print("Random Forest trained successfully.")

Random Forest trained successfully.


## Make Predictions

We use the trained Random Forest to predict delivery times for the test data.


In [34]:
rf_pred = rf_model.predict(X_test)

print("First 10 predictions:")
print(rf_pred[:10])

First 10 predictions:
[23.63 24.14 17.02 39.54 23.82 39.65 14.55 22.36 25.67 48.74]


## Evaluate the Random Forest

We evaluate the Random Forest using MAE, MSE, RMSE, and R².

These metrics will later be compared with the other candidate models.


In [35]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions
rf_pred = rf_model.predict(X_test)

# Metrics
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_pred)

# Adjusted R²
n = len(y_test)
p = X_test.shape[1]

rf_adjusted_r2 = 1 - (1 - rf_r2) * (n - 1) / (n - p - 1)

# Display results
print("Random Forest Results")
print("---------------------")
print("MAE        :", round(rf_mae, 2), "minutes")
print("MSE        :", round(rf_mse, 2))
print("RMSE       :", round(rf_rmse, 2), "minutes")
print("R²         :", round(rf_r2, 4))
print("Adjusted R²:", round(rf_adjusted_r2, 4))

Random Forest Results
---------------------
MAE        : 3.66 minutes
MSE        : 22.14
RMSE       : 4.71 minutes
R²         : 0.7509
Adjusted R²: 0.7501


### Interpretation

The Random Forest model achieves a **MAE of 3.67 minutes**, which means that the model's predictions are wrong by approximately **3.67 minutes on average**.

The model also achieves an **RMSE of 4.72 minutes** and an **R² of 0.7496**, meaning that it explains approximately **74.96% of the variation in delivery time** on the test set.

Compared with Linear Regression and a single Decision Tree, Random Forest provides better test-set performance. It is therefore a strong candidate for the next step: **hyperparameter optimization**.


## Train vs Test Evaluation — Overfitting

A model should perform well not only on the training data, but also on unseen test data.

We compare the training and test performance using **MAE, RMSE, R², and Adjusted R²**.

If the training performance is much better than the test performance, the model may be **overfitting**.

A small difference between training and test performance indicates better generalization.


In [36]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


def evaluate_model(model, X_train, y_train, X_test, y_test):
    # Predictions
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    # ---------- TRAIN ----------
    train_mae = mean_absolute_error(y_train, train_pred)
    train_mse = mean_squared_error(y_train, train_pred)
    train_rmse = np.sqrt(train_mse)
    train_r2 = r2_score(y_train, train_pred)

    n_train = len(y_train)
    p_train = X_train.shape[1]

    train_adjusted_r2 = (
        1 - (1 - train_r2) * (n_train - 1)
        / (n_train - p_train - 1)
    )

    # ---------- TEST ----------
    test_mae = mean_absolute_error(y_test, test_pred)
    test_mse = mean_squared_error(y_test, test_pred)
    test_rmse = np.sqrt(test_mse)
    test_r2 = r2_score(y_test, test_pred)

    n_test = len(y_test)
    p_test = X_test.shape[1]

    test_adjusted_r2 = (
        1 - (1 - test_r2) * (n_test - 1)
        / (n_test - p_test - 1)
    )

    return {
        "Train MAE": train_mae,
        "Test MAE": test_mae,
        "Train MSE": train_mse,
        "Test MSE": test_mse,
        "Train RMSE": train_rmse,
        "Test RMSE": test_rmse,
        "Train R²": train_r2,
        "Test R²": test_r2,
        "Train Adjusted R²": train_adjusted_r2,
        "Test Adjusted R²": test_adjusted_r2
    }


# Evaluate all three models
linear_results = evaluate_model(
    model,
    X_train,
    y_train,
    X_test,
    y_test
)

tree_results = evaluate_model(
    tree_model,
    X_train,
    y_train,
    X_test,
    y_test
)

rf_results = evaluate_model(
    rf_model,
    X_train,
    y_train,
    X_test,
    y_test
)


# Display results
for model_name, results in [
    ("Linear Regression", linear_results),
    ("Decision Tree", tree_results),
    ("Random Forest", rf_results)
]:
    print(f"\n{model_name}")
    print("-" * len(model_name))

    print("Train MAE        :", round(results["Train MAE"], 2), "minutes")
    print("Test MAE         :", round(results["Test MAE"], 2), "minutes")

    print("Train MSE        :", round(results["Train MSE"], 2))
    print("Test MSE         :", round(results["Test MSE"], 2))

    print("Train RMSE       :", round(results["Train RMSE"], 2), "minutes")
    print("Test RMSE        :", round(results["Test RMSE"], 2), "minutes")

    print("Train R²         :", round(results["Train R²"], 4))
    print("Test R²          :", round(results["Test R²"], 4))

    print("Train Adjusted R²:", round(results["Train Adjusted R²"], 4))
    print("Test Adjusted R² :", round(results["Test Adjusted R²"], 4))


Linear Regression
-----------------
Train MAE        : 5.09 minutes
Test MAE         : 5.07 minutes
Train MSE        : 41.55
Test MSE         : 41.24
Train RMSE       : 6.45 minutes
Test RMSE        : 6.42 minutes
Train R²         : 0.5265
Test R²          : 0.5361
Train Adjusted R²: 0.5261
Test Adjusted R² : 0.5344

Decision Tree
-------------
Train MAE        : 0.0 minutes
Test MAE         : 4.79 minutes
Train MSE        : 0.0
Test MSE         : 40.81
Train RMSE       : 0.0 minutes
Test RMSE        : 6.39 minutes
Train R²         : 1.0
Test R²          : 0.5409
Train Adjusted R²: 1.0
Test Adjusted R² : 0.5393

Random Forest
-------------
Train MAE        : 1.36 minutes
Test MAE         : 3.66 minutes
Train MSE        : 3.07
Test MSE         : 22.14
Train RMSE       : 1.75 minutes
Test RMSE        : 4.71 minutes
Train R²         : 0.965
Test R²          : 0.7509
Train Adjusted R²: 0.9649
Test Adjusted R² : 0.7501


## Overfitting Analysis

The comparison between training and test performance shows different behaviors for the three models.

**Linear Regression** has very similar training and test performance, indicating no significant overfitting. However, its predictive performance remains limited.

**Decision Tree** achieves perfect performance on the training data (`R² = 1.00`) but much lower performance on the test data (`R² = 0.5355`). This indicates strong overfitting: the tree has learned the training data too specifically.

**Random Forest** also shows a gap between training and test performance (`R² = 0.9647` vs `0.7496`), indicating some overfitting. However, its test performance is substantially better than the single Decision Tree, with a **MAE of 3.67 minutes**, **RMSE of 4.72 minutes**, and **R² of 0.7496**.

Random Forest is therefore selected as the candidate model for the next step: **hyperparameter optimization**.


## Hyperparameter Optimization — Random Forest

The Random Forest model achieved the best performance among the initial models, but the difference between training and test performance indicates some overfitting.

To improve the model's generalization, we optimize its hyperparameters using `RandomizedSearchCV`.

`RandomizedSearchCV` tests a number of randomly selected combinations of hyperparameters and evaluates them using cross-validation on the training data.

The test set is not used during the optimization process. It will remain reserved for the final evaluation of the optimized model.

The main hyperparameters we will optimize are:

* `n_estimators`: number of trees in the forest.
* `max_depth`: maximum depth of each tree.
* `min_samples_split`: minimum number of samples required to split a node.
* `min_samples_leaf`: minimum number of samples required in a leaf.
* `max_features`: number of features considered when searching for the best split.


In [37]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_distributions = {
    "n_estimators": [100, 150, 200],
    "max_depth": [10, 15, 20, 25],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [0.7, 1.0]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=10,
    cv=3,
    scoring="neg_root_mean_squared_error",
    random_state=42,
    n_jobs=-1,
    verbose=1
)

random_search.fit(X_train, y_train)

print("Best parameters:")
print(random_search.best_params_)

print("\nBest CV RMSE:")
print(round(-random_search.best_score_, 2), "minutes")

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters:
{'n_estimators': 150, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.7, 'max_depth': 15}

Best CV RMSE:
4.57 minutes


## Evaluation of the Optimized Random Forest

After hyperparameter optimization, we evaluate the best Random Forest on both the training and test datasets.

We calculate MAE, MSE, RMSE, R², and Adjusted R².

The test results are used to measure the model's performance on unseen data.

The difference between training and test performance is also analyzed to detect possible overfitting.


In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Best optimized model
best_rf = random_search.best_estimator_

# Predictions
train_pred = best_rf.predict(X_train)
test_pred = best_rf.predict(X_test)

# =========================
# Training metrics
# =========================

train_mae = mean_absolute_error(y_train, train_pred)
train_mse = mean_squared_error(y_train, train_pred)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(y_train, train_pred)

n_train = len(y_train)
p_train = X_train.shape[1]

train_adjusted_r2 = 1 - (
    (1 - train_r2) * (n_train - 1)
    / (n_train - p_train - 1)
)

# =========================
# Test metrics
# =========================

test_mae = mean_absolute_error(y_test, test_pred)
test_mse = mean_squared_error(y_test, test_pred)
test_rmse = np.sqrt(test_mse)
test_r2 = r2_score(y_test, test_pred)

n_test = len(y_test)
p_test = X_test.shape[1]

test_adjusted_r2 = 1 - (
    (1 - test_r2) * (n_test - 1)
    / (n_test - p_test - 1)
)

# =========================
# Results
# =========================

print("Optimized Random Forest")
print("-----------------------")

print("\nTraining:")
print("MAE        :", round(train_mae, 2), "minutes")
print("MSE        :", round(train_mse, 2))
print("RMSE       :", round(train_rmse, 2), "minutes")
print("R²         :", round(train_r2, 4))
print("Adjusted R²:", round(train_adjusted_r2, 4))

print("\nTest:")
print("MAE        :", round(test_mae, 2), "minutes")
print("MSE        :", round(test_mse, 2))
print("RMSE       :", round(test_rmse, 2), "minutes")
print("R²         :", round(test_r2, 4))
print("Adjusted R²:", round(test_adjusted_r2, 4))

Optimized Random Forest
-----------------------

Training:
MAE        : 2.83 minutes
MSE        : 13.33
RMSE       : 3.65 minutes
R²         : 0.8481
Adjusted R²: 0.848

Test:
MAE        : 3.57 minutes
MSE        : 20.69
RMSE       : 4.55 minutes
R²         : 0.7673
Adjusted R²: 0.7664


## Evaluation of the Optimized Random Forest

The optimized Random Forest achieves a test MAE of **3.57 minutes** and a test RMSE of **4.55 minutes**.

In business terms, the model's delivery-time predictions are wrong by approximately **3.57 minutes on average**.

The model achieves a test R² of **0.7669**, meaning that it explains approximately **76.69% of the variation** in delivery time.

The training R² is **0.8458**, compared with **0.7669** on the test set. This difference indicates some overfitting, but the model still generalizes well to unseen data.

Compared with the initial Random Forest, the optimized model improves the test MAE from **3.67 to 3.57 minutes**, the RMSE from **4.72 to 4.55 minutes**, and the R² from **0.7496 to 0.7669**.

The optimized Random Forest is therefore selected as the final candidate model.

### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------


## Gradient Boosting Regressor

Gradient Boosting is an ensemble learning algorithm based on decision trees.

Unlike Random Forest, where many trees are built independently, Gradient Boosting builds trees sequentially.

Each new tree tries to correct the errors made by the previous trees.

The final prediction is obtained by combining the predictions of all the trees.

In this project, Gradient Boosting is used to predict `Time_taken(min)`.

In [40]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


# Create the model
gb_model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

# Train
gb_model.fit(X_train, y_train)

# Predictions
y_train_pred_gb = gb_model.predict(X_train)
y_test_pred_gb = gb_model.predict(X_test)


# Evaluation function
def evaluate_model(y_true, y_pred, n_features):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    n = len(y_true)
    adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - n_features - 1)

    return mae, mse, rmse, r2, adjusted_r2


# Training metrics
train_mae, train_mse, train_rmse, train_r2, train_adj_r2 = evaluate_model(
    y_train,
    y_train_pred_gb,
    X_train.shape[1]
)

# Test metrics
test_mae, test_mse, test_rmse, test_r2, test_adj_r2 = evaluate_model(
    y_test,
    y_test_pred_gb,
    X_test.shape[1]
)


# Display results
print("Gradient Boosting")
print("-----------------")

print("\nTraining:")
print(f"MAE        : {train_mae:.2f} minutes")
print(f"MSE        : {train_mse:.2f}")
print(f"RMSE       : {train_rmse:.2f} minutes")
print(f"R²         : {train_r2:.4f}")
print(f"Adjusted R²: {train_adj_r2:.4f}")

print("\nTest:")
print(f"MAE        : {test_mae:.2f} minutes")
print(f"MSE        : {test_mse:.2f}")
print(f"RMSE       : {test_rmse:.2f} minutes")
print(f"R²         : {test_r2:.4f}")
print(f"Adjusted R²: {test_adj_r2:.4f}")

print("\nOverfitting Check:")
print(f"R² gap     : {train_r2 - test_r2:.4f}")
print(f"RMSE gap   : {test_rmse - train_rmse:.2f} minutes")

Gradient Boosting
-----------------

Training:
MAE        : 4.03 minutes
MSE        : 26.23
RMSE       : 5.12 minutes
R²         : 0.7012
Adjusted R²: 0.7009

Test:
MAE        : 4.05 minutes
MSE        : 26.37
RMSE       : 5.14 minutes
R²         : 0.7033
Adjusted R²: 0.7023

Overfitting Check:
R² gap     : -0.0021
RMSE gap   : 0.01 minutes


## Gradient Boosting Hyperparameter Optimization

The initial Gradient Boosting model gave a test RMSE of 5.14 minutes and a test R² of 0.7033.

We now use `RandomizedSearchCV` to test different combinations of hyperparameters.

The goal is to find a configuration that improves the model's performance while maintaining good generalization.

We use RMSE as the scoring metric because it measures prediction error in minutes and gives more importance to larger errors.

In [41]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(
    random_state=42
)

param_distributions = {
    "n_estimators": [100, 150, 200, 250],
    "learning_rate": [0.03, 0.05, 0.08, 0.1],
    "max_depth": [2, 3, 4],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "subsample": [0.8, 1.0]
}

random_search_gb = RandomizedSearchCV(
    estimator=gb,
    param_distributions=param_distributions,
    n_iter=10,
    cv=3,
    scoring="neg_root_mean_squared_error",
    random_state=42,
    n_jobs=-1,
    verbose=1
)

random_search_gb.fit(X_train, y_train)

print("Best parameters:")
print(random_search_gb.best_params_)

print(f"\nBest CV RMSE: {-random_search_gb.best_score_:.2f} minutes")

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters:
{'subsample': 1.0, 'n_estimators': 150, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_depth': 4, 'learning_rate': 0.08}

Best CV RMSE: 4.71 minutes


## Optimized Gradient Boosting

The best hyperparameters found by `RandomizedSearchCV` are used to create the optimized Gradient Boosting model.

We then evaluate the optimized model on both training and test data.

The test results will be compared with the Optimized Random Forest to determine how well the optimized Gradient Boosting model generalizes to unseen data.

In [42]:
# Get the best Gradient Boosting model
best_gb_model = random_search_gb.best_estimator_

# Predictions
y_train_pred_gb_opt = best_gb_model.predict(X_train)
y_test_pred_gb_opt = best_gb_model.predict(X_test)


# Evaluation function
def evaluate_model(y_true, y_pred, n_features):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    n = len(y_true)
    adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - n_features - 1)

    return mae, mse, rmse, r2, adjusted_r2


# Training
train_mae, train_mse, train_rmse, train_r2, train_adj_r2 = evaluate_model(
    y_train,
    y_train_pred_gb_opt,
    X_train.shape[1]
)

# Test
test_mae, test_mse, test_rmse, test_r2, test_adj_r2 = evaluate_model(
    y_test,
    y_test_pred_gb_opt,
    X_test.shape[1]
)


# Display results
print("Optimized Gradient Boosting")
print("---------------------------")

print("\nTraining:")
print(f"MAE        : {train_mae:.2f} minutes")
print(f"MSE        : {train_mse:.2f}")
print(f"RMSE       : {train_rmse:.2f} minutes")
print(f"R²         : {train_r2:.4f}")
print(f"Adjusted R²: {train_adj_r2:.4f}")

print("\nTest:")
print(f"MAE        : {test_mae:.2f} minutes")
print(f"MSE        : {test_mse:.2f}")
print(f"RMSE       : {test_rmse:.2f} minutes")
print(f"R²         : {test_r2:.4f}")
print(f"Adjusted R²: {test_adj_r2:.4f}")

print("\nOverfitting Check:")
print(f"R² gap     : {train_r2 - test_r2:.4f}")
print(f"RMSE gap   : {test_rmse - train_rmse:.2f} minutes")

Optimized Gradient Boosting
---------------------------

Training:
MAE        : 3.67 minutes
MSE        : 21.47
RMSE       : 4.63 minutes
R²         : 0.7553
Adjusted R²: 0.7551

Test:
MAE        : 3.70 minutes
MSE        : 21.79
RMSE       : 4.67 minutes
R²         : 0.7549
Adjusted R²: 0.7540

Overfitting Check:
R² gap     : 0.0005
RMSE gap   : 0.03 minutes


## Conclusion

Several regression models were tested to predict delivery time: Linear Regression, Decision Tree, Random Forest, and Gradient Boosting. The models were then optimized using `RandomizedSearchCV` and cross-validation.

The **Optimized Random Forest** obtained the best test performance:

* **MAE:** 3.57 minutes
* **RMSE:** 4.55 minutes
* **R²:** 0.7673
* **Adjusted R²:** 0.7664

This means that, on average, the model's predictions are about **3.57 minutes away from the actual delivery time**, while the R² indicates that the model explains about **76.7% of the variation** in delivery time.

The optimization also improved the Random Forest's generalization. The R² gap between training and testing decreased from **0.2151** with the initial Random Forest to **0.0808** with the optimized version, indicating less overfitting.

The Optimized Gradient Boosting model also generalized well, with almost no difference between training and testing performance, but its test performance was slightly lower than the Optimized Random Forest.

Therefore, the **Optimized Random Forest is selected as the final model** for the DeliveryETA project because it provides the strongest test performance among the models evaluated while maintaining a reasonable level of generalization.


In [44]:
import joblib

# Get the optimized Random Forest
best_rf_model = random_search.best_estimator_

# Save the model
joblib.dump(
    best_rf_model,
    "../models/delivery_eta_model.joblib"
)

['../models/delivery_eta_model.joblib']

### Create the preprocessing definition

In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numerical_features = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "multiple_deliveries",
    "distance",
    "order_hour",
    "pickup_hour",
    "pickup_delay",
    "month"
]

categorical_features = [
    "Weatherconditions",
    "Type_of_vehicle",
    "Road_traffic_density",
    "day_of_week"
]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

### Create the Pipeline

In [50]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

final_model = Pipeline(
    steps=[
        (
            "model",
            RandomForestRegressor(
                n_estimators=150,
                max_depth=15,
                min_samples_split=2,
                min_samples_leaf=4,
                max_features=0.7,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

### Train the Pipeline

In [49]:
print("X_train columns:")
print(X_train.columns.tolist())

print("\nX_train shape:")
print(X_train.shape)

X_train columns:
['Delivery_person_Age', 'Delivery_person_Ratings', 'multiple_deliveries', 'distance', 'order_hour', 'pickup_hour', 'pickup_delay', 'month', 'Weatherconditions_Cloudy', 'Weatherconditions_Fog', 'Weatherconditions_Sandstorms', 'Weatherconditions_Stormy', 'Weatherconditions_Sunny', 'Weatherconditions_Windy', 'Road_traffic_density_High', 'Road_traffic_density_Jam', 'Road_traffic_density_Low', 'Road_traffic_density_Medium', 'Type_of_vehicle_bicycle', 'Type_of_vehicle_electric_scooter', 'Type_of_vehicle_motorcycle', 'Type_of_vehicle_scooter', 'day_of_week_Friday', 'day_of_week_Monday', 'day_of_week_Saturday', 'day_of_week_Sunday', 'day_of_week_Thursday', 'day_of_week_Tuesday', 'day_of_week_Wednesday']

X_train shape:
(33217, 29)


In [51]:
final_model.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('model', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](29,)","['Delivery_person_Age','Delivery_person_Ratings','multiple_deliveries',..., 'day_of_week_Thursday','day_of_week_Tuesday','day_of_week_Wednesday']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,29
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",150
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",15
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",4
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=1.0The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None or 1.0, then `max_features=n_features`... note:: The default of 1.0 is equivalent to bagged trees and more rand

### Evaluate the final model

In [52]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions on test data
y_test_pred = final_model.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, y_test_pred)
mse = mean_squared_error(y_test, y_test_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_test_pred)

print(f"MAE  : {mae:.2f} minutes")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f} minutes")
print(f"R²   : {r2:.4f}")

MAE  : 3.57 minutes
MSE  : 20.69
RMSE : 4.55 minutes
R²   : 0.7673


### Save the final Pipeline


In [53]:
import joblib

joblib.dump(
    final_model,
    "../models/delivery_eta_pipeline.joblib"
)

['../models/delivery_eta_pipeline.joblib']